[tools]
pre-commit = "4.6.2"
python = "3.14"
terraform = "1.15.8"
terraform-docs = "0.24.0"

[tasks.terraform-docs]
description = "Generates terraform docs for all modules"
run = "terraform-docs markdown table --output-file README.md ."
