---
fail_fast: false

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_docs
        args:
          - "--args=--config=.terraform-docs.yaml"
      - id: terraform_fmt
